### ISSUE TITLE
Unable to install in Ubuntu 16.04

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#11]
I am getting the following error after executing
````
warden up
```
> ERROR: Command `docker-compose -p warden -f docker/docker-compose.yml up -d "${WARDEN_PARAMS[@]}" "$@"` on line 23 failed with exit code 1

**Comment by davidalger** [comment]
@MagePsycho Was there any error output other than the trap noting the exit code from docker-compose? Can you tell me, what version of Docker and docker compose you have installed? 

```
docker -v
docker-compose -v
```

As the README notes, I've only tested this on Ubuntu 18.10 and Fedora 29 as far as Linux OSs go, so I'm not 100% it works on Ubuntu 16, but I wouldn't expect docker-compose to be the failure point (unless docker-compose is perhaps not installed properly). I plan to setup an Ubuntu 16.04.06 LTS VM to install and see where it leads.

**Comment by davidalger** [comment]
Setup an Ubuntu 16 in a VM. The full error message is as follows:
```
ERROR: Version in "./docker/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

ERROR: Command `docker-compose -p warden -f docker/docker-compose.yml up -d "${WARDEN_PARAMS[@]}" "$@"` on line 23 failed with exit code 1
```

As the first ERROR message indicates, the docker compose version which ships to Ubuntu 16 LTS is too old and unsupported. `docker-compose` version 1.18.0 is when support for Compose file version 3.5 was introduced. Digital Ocean has a blog post showing how to install a newer version of docker compose on Ubuntu 16:
https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-16-04

Once in place, Warden will start succesfully, but there is (as I suspected would be the case) issues with automatic DNS resolution. The dnsmasq container starts, but due to differences between Ubuntu 16 and 18 as far as how they perform name resolution, for the auto-DNS warden provides, for this to work on Ubuntu 16 you'll want to `touch ~/.warden/nodnsconfig` then `warden install && warden up`; once that is disabled, configure the use of 127.0.0.1 as your nameserver in your network configuration (if you want to take advantage of dnsmasq).

I'd welcome (and be more than willing to test a PR which updated the install routine to add support for configuring DNS on Ubuntu 16, as long as it maintained compatibility with new Linux OSs. Since, per the README, Ubuntu 16 is unsupported and I don't personally have the time to do this, I'm going to go ahead and mark this issue as closed.
