### ISSUE TITLE
[Question] Is possible to set static ip for LAN access 

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#118]
Imagine we have success setup magento instance but want to share access to another computer in LAN network
example another computer can access through browser from http://192.x.x.x/test
local: http://app.warden.test <= working
LAN: http://192.x.x.x (this ip is ip local machine)
I'm not sure we should use lan ip or this feature already support by (traefik)

**Comment by mrtuvn** [comment]
i have take a look at this but not figure out how to do
https://docs.warden.dev/services.html

**Comment by davidalger** [comment]
This is most certainly possible! I know because I'm doing it myself :) Have projects running via Warden on one machine, and I access them from two other machines I've got on a regular basis.

What won't work, is accessing  http://app.warden.test on 192.x.x.x/test (the URLs are not the same). What will work, is adding entries to /etc/hosts on the requesting machine or having your router answer DNS queries for *.test with the IP address of the machine you are running Warden on.

To do this, you need to set `TRAEFIK_LISTEN=0.0.0.0` as it mentions in that docs page and then run `warden up` to apply the change. When that is done, you can check to see if it took by inspecting the output of `docker ps | grep traefik` or use one of the following to verify Traefik is listening publicly:

```
# for macOS
sudo lsof -i -n -P | grep LISTEN | grep :443

# for Linux
sudo netstat -plunt | grep docker | grep :443
```

Once this is done, you should be able to connect to that machine by hitting it's IP address (replace 123.123.123.123 with the IP of the machine running warden):

```
curl -v --resolve app.warden.test:443:123.123.123.123 https://app.warden.test
```

If you've gotten this far, then you've got things working. The next step would be to either:

a) Add an entry to /etc/hosts for the domain; or

b) Configure your router or DNS server to respond to *.test queries with the IP address of the machine on which you run Warden so anyone on the local network can browse to the site using the .test domain.

**Comment by mrtuvn** [comment]
hostname with my url was found in DNS cache after run command as you mentioned
Added ip to /etc/hosts
192.168.2.xxx app.warden.test

Try to access magento instance via my mobile phone (connected via wifi) but not success
