### ISSUE TITLE
Introduce request: Use one subdomain for multiple projects

### ISSUE THREAD

**Issue by Den4ik** [davidalger/warden#122]
**Idea:**

Currently I should generate certificates for each project and use something like `app.project.test` as domain.
It would  be good to use domains like `project.magento2.test`, `project.magento1.test`, `project.laravel.test`

In this case I need generate one wildcard certificate for all projects and urls looks more clear

**Comment by davidalger** [comment]
@Den4ik I'm not sure this is somewhere I'd like to go with this project. Using domains in this way would have confusing semantics, and would result in conflicts for the domains generated for auxiliary services for things like Mailhog and RabbitMQ which both run on a per-project basis at mailhog.project.test and rabbitmq.project.test currently.

The use of a root CA to sign SSL certificates was done because by-design each project should have a separate domain name. If you're merely concerned about the manual step during setup for other devs working on the project, perhaps adopting an init script similar to this one would be a good idea (the repo this is in mirrors how I and my colleagues at Mediotype setup each Magento project to get started):
https://github.com/davidalger/warden-env-magento2/blob/develop/tools/init.sh

Appreciate the suggestion, but I'm going to go ahead and close this one out.
