### ISSUE TITLE
Error SEC_ERROR_BAD_SIGNATURE in broser importing Root CA certificate

### ISSUE THREAD

**Issue by gfilice** [davidalger/warden#130]
After import the ca.cert.pem from ssl/rootca/certs folder in Firefox Authorities Tab, I receive the SEC_ERROR_BAD_SIGNATURE accessing to all .test local domains (https://traefik.warden.test/, ecc.). I must remove the Warden Autority no access these domains (with https alert).

**Comment by davidalger** [comment]
This error generally happens when there is a CA root loaded with a common name matching what was used to sign SSL certificates, but this CA root added to the browser wasn't actually the one used to sign the SSL certificate being sent. Because it wasn't used to sign the certificate, but the common name of the CA root and the name of the "issuer" on the SSL certificate match it causes an error.

What I would suggest is the following:

a) Remove everything in `~/.warden/ssl/certs/` and `~/.warden/ssl/rootca/`

b) Ensure there are no CA certificates in your Keychain (macOS) or Firefox settings.

c) Run `warden install` to generate a new CA root

d) Re-sign certificates for each of your .test domains using `warden sign-certificate`

**Comment by gfilice** [comment]
Removed all in ~/.warden/ssl/certs/ and ~/.warden/ssl/rootca/. 
Run warden install but no files are created  in ~/.warden/ssl/certs/ and ~/.warden/ssl/rootca/. 
The only message from warden install is 
==> Configuring resolver for .test domains (requires sudo privileges)

**Comment by davidalger** [comment]
Perhaps remove the entire `~/.warden/ssl` directory and try again. It's pretty simple really, just looking to see if these exist, and if not it generates a new CA root when running `warden install`:
https://github.com/davidalger/warden/blob/develop/commands/install.cmd#L16-L36

**Comment by gfilice** [comment]
Deleted entire ~/.warden/ssl, but when i launch warden install i receive the following error:

==> Generating private key for local root certificate
genrsa: Can't open "/root/.warden/ssl/rootca/private/ca.key.pem" for writing, No such file or directory

ERROR: Command `openssl genrsa -out "${WARDEN_SSL_DIR}/rootca/private/ca.key.pem" 2048` on line 26 failed with exit code 1

**Comment by davidalger** [comment]
Are you running warden with sudo? Or is `/root` really your home directory? The command immediately preceding the one that's throwing that error is making that directory:
```
if [[ ! -d "${WARDEN_SSL_DIR}/rootca" ]]; then
    mkdir -p "${WARDEN_SSL_DIR}/rootca"/{certs,crl,newcerts,private}

    openssl ...
fi
```
If this is not working, I'm afraid you might need to do some digging on your own to figure out why. Suggestion no one though would be to not run warden install as root or sudo (if you are in fact are, as it appears).

**Comment by gfilice** [comment]
I solved the problem generating manually a new CA root certificate.
Now it works fine.
