### ISSUE TITLE
Please enable way for Multi Domain option other than .test with ssl support

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#14]
How to setup Multi Domain to one magento instance of Warden environment?  Something like 

> store1.domain.local
> store2.domain.local
> store1.domain.com
> store2.domain.com

**Comment by davidalger** [comment]
Hi @Elamurugan-Nallathambi - thanks for the question! This is actually possible with a little bit of additional configuration in the project. 

You can sign SSLs for any domain of your choice, either multiple separate certs:
```
warden sign-certificate foo.test
warden sign-certificate foo.test
```
OR a single SSL with multiple wildcards on the SAN:
```
warden sign-certificate foo.test bar.test
```
Traefik will simply use whichever certificate has a matching hostname when it terminates TLS, routing the request to the appropriate container based on the labels it uses for routing.

In the project, you'll need to add a file at `.warden/warden-env.yml` (this will be additive to the docker-compose config Warden uses for the env, anything added here will be merged in, and you can see the complete config using `warden env config`):

```
version: "3.5"
services:
  varnish:
    labels:
      traefik.frontend.rule: Host:${TRAEFIK_HOST_LIST}
```

Then add something like this to the `.env` file with a comma separated list of host names:
```
TRAEFIK_HOST_LIST=store1.domain.local,store2.domain.local
```
Once you do that, `warden env up -d` to update the containers and bam, each of the URLs should work as expected.

Given your noted use of *.local and *.com domains, it's worth noting the default dnsmasq and resolver configuration isn't going to catch these addresses for you on macOS since it's only used to resolve the .test TLD, so you'll likely want to go ahead and use entries in /etc/hosts for those — haven't tested it, but you might be able to edit the dnsmasq config via https://dnsmasq.warden.test/ to resolve those addresses if you're on linux without too much hassle.

**Comment by davidalger** [comment]
Quick note: An updated docs page outlining a Warden 0.2.0 compliant method of doing this has been added here: https://docs.warden.dev/configuration/multipledomains.html
