### ISSUE TITLE
Feature Request: PHP 7.4

### ISSUE THREAD

**Issue by navarr** [davidalger/warden#144]
Magento 2.4 will support PHP 7.4

**Comment by davidalger** [comment]
Challenge here currently is the state of IUS RPMs currently not having PHP 7.4 for some (seemingly unknown reason): https://github.com/iusrepo/wishlist/issues/251 Seems movement over there has slowed and I haven't had the time (yet!) to see if I can address it some other way. CentOS 8 ships with 7.2 and has 7.3 available via AppStreams, but does not yet have a stream for 7.4 last I checked (and if it did, there would surely be some extensions that would need to be compiled rather than the simple install from IUS currently).

**Comment by davidalger** [comment]
Spent a little time this afternoon digging through existing spec files and figuring out how to build them on some clean CentOS 7 droplets over at Digital Ocean: https://gist.github.com/davidalger/cdc56efb1bbb1140d2315a355379bafc

And then tonight began putting stuff together into a preliminary build to create RPM artifacts for installing PHP 7.4 from up until whatever is holding up these packages on IUS is resolved (think it's something to do with a want with an upstream pkg in a tracker somewhere 🤷 )

When it finishes building, there should be a `php74-rpms.zip` artifact resulting from the latest github action on this branch on my upstream PHP docker image repository: https://github.com/davidalger/docker-images-php/tree/php74 Once that completes, I hope to see what I can do to build a docker image from it, and assuming that is successful, then I'll see if I can sort out the spec files for the remaining pecl packages.

**Comment by davidalger** [comment]
Just to link the two and so I have all my notes in one place, I opened this PR to bump the PHP version to latest of 7.4.5 on the IUS repo as well: https://github.com/iusrepo/php74/pull/4

**Comment by davidalger** [comment]
PHP 7.4 base images have been [added to the upstream docker image repository](https://github.com/davidalger/docker-images-php/commit/cbae946d5190765fab3b72dd0c5ed6c19f1a8b24) with the following note:

> PHP 7.4 images are currently using a custom pipeline to build RPMS from spec files to workaround issues with upstream dependencies which are holding up the process of getting PHP 7.4 published in IUS repositories. These can be found inside the container image at `/var/php74` and `/var/php74-src` where they are located for use as a local RPM repository.

The only difference module wise between 7.3 and 7.4 is that `wddx` is no longer bundled with PHP by default and thus it's not included in the RPMs I built:

```
davidalger@hylfing:08:34 AM:~$ diff -u <(docker run --rm davidalger/php:7.3 php -m) <(docker run --rm davidalger/php:7.4 php -m)
--- /dev/fd/63	2020-04-29 08:35:01.120581978 -0500
+++ /dev/fd/62	2020-04-29 08:35:01.120581978 -0500
@@ -50,7 +50,6 @@
 sysvsem
 sysvshm
 tokenizer
-wddx
 xml
 xmlreader
 xmlrpc
```

To build these I utilized the following updated and/or new spec files for the php74 build. These will likely be moved to the iusrepo account when php74 is officially published on the IUS repository.

* [kelnei/oniguruma6](/kelnei/oniguruma6)
* [davidalger/php74](/davidalger/php74)
* [kelnei/php74-pecl-apcu](/kelnei/php74-pecl-apcu)
* [kelnei/php74-pecl-igbinary](/kelnei/php74-pecl-igbinary)
* [kelnei/php74-pecl-msgpack](/kelnei/php74-pecl-msgpack)
* [kelnei/php74-pecl-redis](/kelnei/php74-pecl-redis)
* [davidalger/php74-pecl-amqp](/davidalger/php74-pecl-amqp)
* [davidalger/php74-pecl-imagick](/davidalger/php74-pecl-imagick)
* [davidalger/php74-pecl-xdebug](/davidalger/php74-pecl-xdebug)
* [davidalger/php74-pecl-zip](/davidalger/php74-pecl-zip)

Due to the updated oniguruma6 library, a custom version of jq had to be built for inclusion as well since jq in epel RPMs links to the old and conflicting oniguruma soname. 

Will be pushing a commit momentarily to this repo triggering a build of PHP 7.4 images with the Warden extras and tagging nomenclature.

**Comment by davidalger** [comment]
Images for using Warden are [available on Quay](https://quay.io/repository/warden/php-fpm?tab=tags). Use these by setting `PHP_VERSION=7.4` in the project's `.env` file, and as always, let me know if you run into any issues with them.
