### ISSUE TITLE
2.3.5 fastcgi_buffers issue

### ISSUE THREAD

**Issue by chris-brabender** [davidalger/warden#153]
It appears in 2.3.5 there are larger headers being sent from Magento so we are seeing errors being thrown in nginx.

We found tweaking the config to this resolved the issue:

    fastcgi_buffers 16 16k; 
    fastcgi_buffer_size 32k;

**Comment by davidalger** [comment]
Made a change to these in c7f4811893 to line up with what I've generally deployed to production M1 and M2 environments (where I've seen this in the past with large X-Mageto-Tags headers). Mind pulling latest images and checking to see those errors go away with this slightly different set of settings? I believe it's the `fastcgi_buffer_size` that's likely the issue, since the original setting of `1024 4k` on the first allows for more total memory than `16 16k`

**Comment by davidalger** [comment]
Closing this issue for now due to inactivity. Feel free to reopen should the change noted above fail to remedy the situation.
