### ISSUE TITLE
Issue with docker-entrypoint permissions

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#156]
when i try to start env got error 126
tested in version 0.5.0

docker v19.03.8
ubuntu 18.04

![Screenshot from 2020-05-25 12-05-01](https://user-images.githubusercontent.com/1908873/82780019-fb289f00-9e7f-11ea-93b2-528aad4c56e6.png)
@davidalger can you review this
I have no ideas why this happens. Try to removed/reinstalled docker with same version But not any lucks. Container php_fpm can't start

**Comment by davidalger** [comment]
These are files embedded in the container images and as it's happening on every one of the containers, I'd say it sounds like something is grossly messed up with your docker volume storage and beyond the realm of what I can make the time to support here on this project. If it were macOS, I'd say probably reset Docker Desktop. You might try stopping docker and completely scrubbing everything it touches. Since this is more a general linux / docker problem, I'm going to mark this as closed.
