### ISSUE TITLE
quay.io - Provide alternative for docker images

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/warden#157]
Right now quay.io has an outage, as result we can't download docker images
![image](https://user-images.githubusercontent.com/1873745/83146122-7eefbf00-a0fe-11ea-93b4-f77f3d544a91.png)

Maybe it's better to add all images to docker hub?

**Comment by lbajsarowicz** [comment]
You can use
```
warden env pull --ignore-pull-failures || true
```
for the time of failure :-)

**Comment by ihor-sviziev** [comment]
I just tried to download images on new machine and it can’t download the
images

**Comment by davidalger** [comment]
Same exact errors here ([screenshot](https://dropshare-ot3kdw.s3.amazonaws.com/uLum9y/Screen-Shot-2020-05-28-08-20-59.35-mMY4ZZzFKl1b.png)). **Big ouch Quay**

When I moved the images to Quay back in January it was largely for 2 reasons:

a) Needed to split images into repository per image for better tag structure (they already had to be renamed beyond just the prefix)
b) Wanted to see the results of their image scanning (which hasn't proved that useful for dev images)

Since that time I've discovered there is no way to have a transparent image caching server in front of Quay — as I do with Docker Hub to avoid downloading images multiple times to individual workstations and VMs — and they've had a major outage at least three times. Apparently the assumption that Quay as a long-standing image registry now owned by RedHat would mean it stayed online and was stable was misplaced. They were down for almost the entire day on the 19th and have been down for nearly an hr now. 🤦 

Thanks for the heads up @ihor-sviziev; might not have noticed it myself this morning. Think the verdict is clear, the images need to be moved back to Docker Hub, the question that remains is where and what the names should be.

These are the current images loading from Quay.io:
```
davidalger:08:36 AM:/opt/warden (develop) $ ack -C 0 -h quay.io environments | sort -n | cut -d : -f2 | awk '{print $1}' | uniq
quay.io/warden/elasticsearch
quay.io/warden/mailhog
quay.io/warden/mariadb
quay.io/warden/mysql
quay.io/warden/nginx
quay.io/warden/php-fpm
quay.io/warden/rabbitmq
quay.io/warden/redis
quay.io/warden/varnish
```

The org name `warden` is not available on Docker Hub as it is currently assigned to an individual. 😞 So I either have to push them into `davidalger` namespace using periods / dashes (repository names can contain alphanumeric characters and the special characters `.`, `_`, or `-`)

```
davidalger:08:36 AM:/opt/warden (develop) $ ack -C 0 -h quay.io environments | sort -n | cut -d : -f2 | awk '{print $1}' | uniq | sed 's#quay.io/warden/#docker.io/davidalger/warden.#'
docker.io/davidalger/warden.elasticsearch
docker.io/davidalger/warden.mailhog
docker.io/davidalger/warden.mariadb
docker.io/davidalger/warden.mysql
docker.io/davidalger/warden.nginx
docker.io/davidalger/warden.php-fpm
docker.io/davidalger/warden.rabbitmq
docker.io/davidalger/warden.redis
docker.io/davidalger/warden.varnish
```

...OR select an alternate name for use as an Org on Docker Hub to push them into. I'd go with `docker.io/warden.dev/<type>` but seems periods are not allowed in org names.

Thoughts? I'm leaning towards using periods with individual repositories under the davidalger namespace on Docker Hub.

**Comment by davidalger** [comment]
Quick update here: All docker images have been re-located to a [new Docker Hub organization](https://hub.docker.com/u/wardenenv) and Warden 0.5.1 released with updated environment configuration referencing these images. See the release notes for further details: https://docs.warden.dev/changelog.html#version-0-5-1-2020-05-28
