### ISSUE TITLE
Magento 2 Sometimes Requires Larger Nginx FastCGI Buffer Configuration

### ISSUE THREAD

**Issue by mike-keilty** [davidalger/warden#160]
Very often, I find myself having to increase the `fastcgi_buffers` and `fastcgi_buffer_size`

I think right now `fastcgi_buffers` is set to 1024 4k, and in some instances I need to increase this to handle elasticsearch pages.  I've had to increase `fastcgi_buffers` to 1024 8k and set a variable for `fastcgi_buffer_size` to 32k.  I think the default should have a reasonable `fastcgi_buffer_size` set for nginx.

**Comment by davidalger** [comment]
@mike-keilty Are you able to share what the size of the catalog is when you run into this? I.e. number of categories, products, products-per-category (and what type), etc? I think this probably has less to do with Elasticsearch than it does with X-Magento-Tags and CSP related headers Magento responds with.

The defaults (just for easy reference here) are:
```
    fastcgi_buffers 1024 4k;
    fastcgi_buffer_size 128k;
```

Basically I'd like to re-create the issue over here so I can figure out what would make sense to put here as reasonable defaults long-term since [this isn't the first time this has come up](https://github.com/davidalger/warden/issues/153) with recent versions of M2)
