### ISSUE TITLE
[Improve] Disable xdebug by configuration

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#176]
Should we allow to config enable/disable in env file before containers up. Most of time we only need that when debugging. Dev will determine whenever to run up xdebug instead start by default
Example
ENABLE_XDEBUG=1

**Comment by davidalger** [comment]
The two containers php-fpm and php-debug is by design and as running the debug container has no more overhead than running a 2nd fpm pool there is little reason to make the php-debug container optional when php-fpm is running. Doing so would make for a more confusing developer experience, as there would then be more things to check and steps to run through when preparing to debug. The intention here is for launching into debugging on a Warden environment be as simple as clicking the Enable Xdebug button from the Xdebug Helper browser extension and refreshing the page.
