### ISSUE TITLE
Shopware 6 watchers

### ISSUE THREAD

**Issue by BrentRobert** [davidalger/warden#178]
Hi,

Using the development or production template of Shopware 6 it's possible to use watchers to build your frontend and administration. The ports used by this watcher are not open, therefore they can not be used in warden.

You can see the ports used in the docker-compose.override in the development repository:
https://github.com/shopware/development/blob/6.2/dev-ops/docker/docker-compose.override.yml

Is this something that can be implemented? I would love to use warden to develop on Shopware 6, but without the watchers  it's a bit harder.

Kind regards
Brent

**Comment by navarr** [comment]
As a workaround, you can customize warden images per environment by adding a `.warden/warden-env.yml` file that is merged with the images.

Service names for shopware include `nginx`, `php-fpm`, and `php-debug` among others.

**Comment by BrentRobert** [comment]
I tried setting it up, but it seems opening ports on the php-fpm container alone is not going to be enough.
I also see the problem that the proxies will not work when using the php-debug container then. As we can't open the same port on two different containers.

I don't know how to fix these things :)

**Comment by davidalger** [comment]
@BrentRobert Is there documentation you could point me to on how these watchers are expected to be used as part of the frontend dev workflows at play here?

**Comment by BrentRobert** [comment]
@davidalger Sadly there's not that much right now.
https://github.com/shopware/storefront

The two watchers are ./psh.phar storefront:watch and ./psh.phar administration:watch
Both are using webpack as far as I know.

**Comment by BrentRobert** [comment]
The storefront one is calling: npm --prefix vendor/shopware/storefront/Resources/app/storefront/ run-script hot-proxy
Which is a script for 'NODE_ENV=development MODE=hot node ./build/start-hot-reload.js'.

The administration one is calling:
npm run --prefix vendor/shopware/administration/Resources/app/administration/ dev -- ${APP_URL}
Which calls: node build/dev-server.js

**Comment by BrentRobert** [comment]
The storefront starts a proxy on port 9998. Although this gives issues using TLS I think.

**Comment by BrentRobert** [comment]
@davidalger any way I can be of more assistance in this issue? Would love to be able to switch to warden.

**Comment by ragfire** [comment]
@BrentRobert Have you tried to open the php-fpm ports?

yourProject/.warden/warden-env.yml
`version: "3.5"

services:
  php-fpm:
    ports:
      - 8888:8888
`

then execute the script on the php-fpm container. I've created a makefile. So just replace those vars by our own
WORK_DIR = /var/www/html
APP_URL = https://sh6.test
APP_ENV = dev

`php bin/console bundle:dump
	PROJECT_ROOT=$(WORK_DIR) APP_URL=$(APP_URL) APP_ENV=$(APP_ENV) PORT=8888 HOST=0.0.0.0 ESLINT_DISABLE=true ENV_FILE=$(WORK_DIR)/.env npm run --prefix vendor/shopware/platform/src/Administration/Resources/app/administration dev`

The watcher should be accessibly at [http://localhost:8888](http://localhost:8888).
I hope that works for you.

**Comment by m4m-simon** [comment]
this is still not working...

I opened the Port in `.warden/warden-env.yml`:

```
version: "3.5"
services:
  php-fpm:
    ports:
      - "9998:9998"
```

Then i start `./psh.phar storefront:hot-proxy` in the php-fpm container.

When i then try to connect to localhost :9998 i get the following message from the hot-proxy service:
`Rejecting request "GET app.shopware6.test/" on proxy server for "app.shopware6.test:9998"`

I think we need to configure warden so that i can connect to the port of the container via `app.shopware6.test:9998` instead of `localhost:9998`, but how to do that?

**Comment by m4m-simon** [comment]
can we bring this to work somehow?

**Comment by m4m-simon** [comment]
I think there is an SSL Problem...

because with the port opened and hot-proxy NOT started, i got these errors:
PR_END_OF_FILE_ERROR (Firefox)
ERR_CONNECTION_CLOSED (Chrome)

when i start hot-proxy, these errors change:
SSL_ERROR_RX_RECORD_TOO_LONG (Firefox)
ERR_SSL_PROTOCOL_ERROR (Chrome)

how can we solve this?
is it possible to use warden without https? 
http://app.shopware6.test:9998/
