### ISSUE TITLE
[M2] Test Queues and Exchanges exist in RabbitMQ after env-init

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#179]
In a fresh new environment, the Magento 2 integration test queues and exchanges exist in RabbitMQ.
This doesn't do any harm, it's only makes the system seem less pristine than it does otherwise.

<img width="786" alt="Bildschirmfoto 2020-07-06 um 10 57 31" src="https://user-images.githubusercontent.com/72463/86575503-aba5ba80-bf77-11ea-967c-29c17df9f8b6.png">
<img width="741" alt="Bildschirmfoto 2020-07-06 um 10 57 22" src="https://user-images.githubusercontent.com/72463/86575513-b3655f00-bf77-11ea-9880-883e18500b48.png">

**Comment by davidalger** [comment]
I did a little investigation here, as these queues should not be present in a new setup. In fact the rabbitmq container image (at the time of this writing) is pretty much an unchanged official rabbitmq image, i.e. `rabbitmq:3.8-management` (or 3.7 version) is tagged and pushed to wardenenv/rabbitmq to support future changes if/when they come. So it just starts and doesn't really do anything to setup data regardless of environment type.

Since it started up with Magento specific queues and exchanges in there, it sounds like there was something leftover from a previous instance of M2. Is it possible the name of the environment had previously been used, and there was a left-over anonymous volume which the new environment picked up and linked with the RabbitMQ container?

When spinning down environments one is completely done with, I recommend specifying the `-v` flag to clean up any volumes associated with the project containers (both named volumes such as `exampleproj_dbdata` used by MariaDB as well as anonymous volumes used by some services like RabbitMQ and Redis): `warden env down -v` 

Perhaps it'd be a good idea to declare volumes in the compose config for these so the volumes these two container images setup will create named rather than anonymous volumes making them more obvious if one runs `docker volume ls` on their system. I may do this in a future release.

**Comment by Vinai** [comment]
Hmm, maybe there was an older volume left over from the last time I started using warden as my dev environment.
I'll assume it was so and close the issue, sorry for wasting your time!
