### ISSUE TITLE
How to uninstall Warden?

### ISSUE THREAD

**Issue by rafaelstz** [davidalger/warden#183]
I was doing some tests, but I want to uninstall it completely from my machine for now.
How could I uninstall Warden completely?

**Comment by davidalger** [comment]
@rafaelstz Are you on Linux or Mac OS? The basics will be the same, but there are a couple slight differences relating to DNS.

You'll want to run `warden env down -v` in each project you had up and then `warden svc down -v` to cleanup containers, associated volumes, etc for everything Warden ran for projects and for global services. Once this is done, there are files in `~/.warden` which may be cleaned up (this is where Warden stashes generated certificates and misc errata relating to global services such as Traefik).

On Mac OS, there is a file at `/etc/resolver/test` which is responsible for causing *.test DNS queries to route to the `dnsmasq` container. On Linux it's a little more complicated. Some systems will be auto-configured per the logic here (https://github.com/davidalger/warden/blob/develop/commands/install.cmd#L58-L87) but some it simply fails (I'm actually planning to remove this and direct Linux users to a docs page on how to configure their DNS resolver since it's near impossible to cover all Linux configurations, and the references to systemd throw warnings on WSL2 since it's not available).

On Mac OS, there you'll find a Warden issued root CA has been added to the Keychain in order to have trusted SSL certificates for `*.test` sites. It can be removed without causing any harm. On Linux this same root CA will have been added to either `/etc/pki/ca-trust/source/anchors` or `/usr/local/share/ca-certificates` depending on the flavor of Linux you're running.

Lastly there is (an easily identified) block of configuration added to `/etc/ssh/ssh_config` for the connections to `tunnel.warden.test` which can be removed.

This is all written up off-hand, so I can't promise I won't have missed anything, but I believe this covers everything. My goal here has been to leave as few "artifacts" outside of the Docker containers as possible.

**Comment by VivekShingala** [comment]
Hi @davidalger 

How to delete a specific site to reclaim the space on unused projects?

**Comment by navarr** [comment]
> Hi [@davidalger](https://github.com/davidalger)
> 
> How to delete a specific site to reclaim the space on unused projects?

> You'll want to run warden env down -v

Running that against a project deletes all containers and volumes for it
