### ISSUE TITLE
Support for Cron?

### ISSUE THREAD

**Issue by jschreck** [davidalger/warden#184]
Based on this PR #80 - do I have it right that currently there's no way to run cron tasks on the php-fpm container?

**Comment by davidalger** [comment]
I have just pushed an update in commit eab353f which will add crontab support to the php-fpm container. Full details can be found here: https://github.com/davidalger/warden/pull/80#issuecomment-664689120

In order to use this, run `warden env pull` to fetch the latest php-fpm images followed by `warden env up` to rebuild the php-fpm container. You should then (for example) be able to run `warden shell -c 'bin/magento cron:install -d'` to install the Magento 2 `cron:run` entry to the crontab, or you can enter via `warden shell` and use `crontab -e` to edit the crontab by hand.

The limitation here currently is that if the php-fpm container is re-created, the crontab will need to be re-installed.
