### ISSUE TITLE
Symfony and Laravel containers dont have mutagen watcher

### ISSUE THREAD

**Issue by Shero-Inc** [davidalger/warden#203]
While working (mainly on the laravel project type) I noticed that there is no Mutagen watcher so files are not synced on Mac. I believe we need to add a laravel/symfony.mutagen.toml file to environments so that we can sync the files properly. 

Has anyone else experienced this issue of files not syncing when new views/controllers/models are created and modified? It seems to effect mainly modifications.

**Comment by davidalger** [comment]
@Shero-Inc I'm definitely open to including a sync configuration for Symfony and Laravel. Currently everything in the webroot should be synchronized between host and container via a native docker mount (with the :cached or :delegated option on Mac OS) If modifications aren't synchronized, perhaps there was something causing Docker to Hiccup?

The `shopware` environment (which is basically Symfony) has a Mutagen sync currently and I added one recently for Magento 1 in commit 7f544e0. In order to do so for all Symfony and Laravel apps, I'd be looking for input on what to exclude from the Mutagen sync and/or bind mount into the container. For example, `/var/**` is excluded for M1 and M2 and `/var` for Shopware. The `pub/media` (M2) `media` (M1) and `public/media` (Shopware) are excluded and then mounted into the container with a `:delegated` mount so that Media is still available but not synced via Mutagen as a nearly infinite number of media files can slow down the code sync.
