### ISSUE TITLE
Putty ssh access doesn't close

### ISSUE THREAD

**Issue by manuelcanepa** [davidalger/warden#226]
Im on windows and have a centos server to this kind of project. Use putty to remote connect to server. When run `warden env up -d` and then logout, putty keep open with no text.

![image](https://user-images.githubusercontent.com/10290593/92518219-622f5100-f1ee-11ea-8958-11f4fc62c581.png)

Repro steps:
- Remote access to server using putty
- Run `warden env up -d`
- Logout (^D or `exit`)

Result:
- Putty keep open with "blank" window

Expected result:
- Putty should close

This window will close if stop `..._php-fpm_N` and `..._php-debug_N` containers that start with the `warden env up` command

**Comment by davidalger** [comment]
This is triggered due to a forwarded SSH agent on the SSH connection, and I'm not sure there is a good way around this apart from either stopping the environment before closing the SSH session, not forwarding your agent, or getting comfortable with having to Control + C when closing the SSH session (i.e. typing Control + C when it hangs like this severs the forwarded socket which is being listened to by the running containers, allowing SSH to terminate completely)

With the SSH agent forwarded the `SSH_AUTH_SOCK` value in your shell on the SSH server is pointed at a unix socket linked to the agent running on the SSH client. When you start a Warden env (from the SSH session with the forwarded agent), the socket which `SSH_AUTH_SOCK` points to is mounted into the php-* containers so that tools such as git and composer can authenticate via SSH using the keys in the agent on a users workstation. This has the side-effect which you have noticed here.

I'm open to ideas on this one. The feature was implemented here: https://github.com/davidalger/warden/pull/121 Currently I'm not sure of a way to successfully mount the auth socket into the running containers without it causing side-effects when also using an SSH session with agent forwarding enabled.

**Comment by manuelcanepa** [comment]
I see that is bigger than i think. With all this data in mind, i will try to research any kind of solution to contribute, ^C does not resolve the issue, and when i say that i stop php-* containers to "release" the terminal, was an attempt to provide more information about. Thanks for reply.

**Comment by ihor-sviziev** [comment]
@manuelcanepa as a workaround I could recommend you to run the ssh via cmd or powershell, as it's available in win 10.
