### ISSUE TITLE
Varnish questions

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/warden#238]
Hi David,

I'm starting using warden on our internal projects, have a few questions about varnish config.
Thank you so much for developing & supporting it!

1. in the default.vcl file in the image varnish 4.1 we have line "# The minimal Varnish version is 6.0". Is there any real things why it shouldn't work? We're using this version on production, so would like to have as close env as possible.
2. I see that in comparison to the default.vcl in the magento core file is quite different, is there any reasons for that? I'd like to have as close config as possible to production
3. I see you have some /health.php file in the varnish config - is it something custom that you're using or it's just a mistake that could be removed?
4. I don't see any exceptions for xdebug headers in varnish, but have special case for blackfire, does it pass xdebug somehow when page is already cached?

**Comment by davidalger** [comment]
> 1. in the default.vcl file in the image varnish 4.1 we have line "# The minimal Varnish version is 6.0". Is there any real things why it shouldn't work? We're using this version on production, so would like to have as close env as possible.

The comment is largely there because it is in the VCL template found in the Magento_PageCache module. Consider it meaningless. Up until recently there were zero differences in the templates Magento bundles for each version of Varnish, but I believe a minor diff or two has crept in now with 6.x being the only officially supported version on latest versions of Magento (2.4+ I think?) — The important part is the `vcl 4.0` at the top, which Varnish 4.1 will understand just fine.

> 2. I see that in comparison to the default.vcl in the magento core file is quite different, is there any reasons for that? I'd like to have as close config as possible to production

The VCL backed into the image is based on this template which I've been deploying Magento 2 into production with for years (which is, in turn, based on the VCL template bundled with Magento): https://github.com/davidalger/ansible-role-varnish/blob/master/templates/magento2.vcl.j2

It is, as you noticed, slightly different than what Magento publishes. The differences are summarized as:

a) Doesn't include the grace mode support that Magento added.

b) Includes Blackfire support (as you may note in my Ansible template, there is an ACL for it), you wouldn't want that as-is in production (without an ACL that is)

c) Includes X-Cache and X-Cache-Hits headers in output instead of spitting out hit/miss info in vendor specific headers only in developer mode (this is simple put useful info, including on a production system).

d) Addition of `X-Requested-With` to vcl_hash because of modules I ran into in the past which served different content on the same endpoint for XHR vs normal GET request.

e) Magento's template includes `req.http.host` in the vcl_hash because an ill-informed individual PR'd a change (Varnish always includes the host in the VCL hash per documentation and I've never had a problem even on multi-site setups without that, so I never added it to my base template…it's just added C code in the proxy)

'a' and 'd' are really the only changes of substance. You should be completely fine to use the template bundled with M2 as-is, or include th

> 3. I see you have some /health.php file in the varnish config - is it something custom that you're using or it's just a mistake that could be removed?

`/health.php` is something I've used in bare-metal systems for the health check on load balancers. Typically just a PHP file that reports "<hostname> UP" indicating varnish -> php-fpm is responsive. Much lighter weight than the pub/health_check.php in Magento, and more appropriate for a hardware load balancer IMO, unless implementing a custom maintenance page in the VCL for example. There's no reason you need this in your production system if you're not using it, just a simple regex change, for which I default to a regex including both for compatibility with either direction.

> 4. I don't see any exceptions for xdebug headers in varnish, but have special case for blackfire, does it pass xdebug somehow when page is already cached?

Given the development nature of these images, I'd perhaps be open to a PR which accomplished the same for Xdebug, but currently if you hit a page cached by Varnish, the response will in fact come from Varnish and NOT pass back to php-debug. The Blackfire one was easy to include since it was something I already included in my base VCL template, along with an ACL to prevent abuse, in line with the VCL snippets published by Blackfire in their docs.

It may be worth noting if you do deploy with a different VCL in production, and wish to maintain full parity, you could use the `.warden/warden-env.yml` to mount a custom VCL into the container at `/etc/varnish/default.vcl.template` to override what's embedded by default.

**Comment by ihor-sviziev** [comment]
@davidalger thank you for quite good explanation. In addition to that I see full history for this template file, now it's fully clear to me what you were doing here  https://github.com/davidalger/ansible-role-varnish/commits/master/templates/magento2.vcl.j2

I'll close this issue

**Comment by sprankhub** [comment]
For those wondering how they can actually implement a custom VCL like suggested here:

> It may be worth noting if you do deploy with a different VCL in production, and wish to maintain full parity, you could use the `.warden/warden-env.yml` to mount a custom VCL into the container at `/etc/varnish/default.vcl.template` to override what's embedded by default.

1. Create a file `.warden/varnish/default.vcl.template` in your project root directory with the VCL of your choice. Make sure to keep the `${BACKEND_HOST}`, `${BACKEND_PORT}` and `${ACL_PURGE_HOST}` in there.
2. Create a file `.warden/warden-env.yml` with the following contents:

        version: "3.5"
        services:
          varnish:
            volumes:
              - ./.warden/varnish/default.vcl.template:/etc/varnish/default.vcl.template
3. Run `warden env up --force-recreate` and enjoy your new VCL file.

**Comment by magenizr** [comment]
Perfect @sprankhub, very helpful! It's working!

Just sharing the first few lines of our `default.vcl.template` which we have copied over from `vendor/magento/module-page-cache/etc/varnish6.vcl`. Placeholders are replaced as per your comment.

```
backend default {
    .host = "${BACKEND_HOST}";
    .port = "${BACKEND_PORT";
    .first_byte_timeout = 600s;
    .probe = {
        .url = "/pub/health_check.php";
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
   }
}

acl purge {
    "${ACL_PURGE_HOST}";
}
```

Note:
- If your Varnish container keeps disappearing, you can use `docker logs PROJECT-varnish-1` to see if there is any syntax error in your VCL file
