### ISSUE TITLE
Could not start env

### ISSUE THREAD

**Issue by torhoehn** [davidalger/warden#24]
On my Mac I created a Magento 2 environment with the Magento 2 GitHub repository and installed the Sample Data directly from GitHub. Everything was running fine. 

After stopping the environment I'm not able to start it again, because the initial synchronisation does not complete. The Docker engine already has 6 GB of RAM available. Do you know any solution for this?
<img width="1392" alt="Screenshot 2019-10-22 at 07 03 55" src="https://user-images.githubusercontent.com/1945725/67312264-55840a80-f501-11e9-9d73-e3d457abdf7e.png">

**Comment by mandatoryhashtags** [comment]
@torhoehn Did you run a sync stop when you stopped the environment?

```
warden sync stop
```

**Comment by torhoehn** [comment]
@mandatoryhashtags I did run:
> warden env stop && warden sync stop

**Comment by davidalger** [comment]
@torhoehn The sync start is looking for the text "watching for changes" in the output of mutagen's list command, so something is sticking. When this happens, take a look at the output of `warden sync list` to find out what it states as the cause (otherwise there is little to go off of for what the problem may be).

For example, if I run this on an environment which hasn't been started since I rebooted my Mac, I get the following output:
```
$ warden sync list
--------------------------------------------------------------------------------
Identifier: 24656500-6a5b-4af9-8759-7ca8b11e11b9
Labels:
	warden-sync: rock
Alpha:
	URL: /Volumes/Server/sites/rock
	Connection state: Connected
Beta:
	URL: docker://915a542fa163de62f05988ffa6a0de48042ba6f8772185a6381a22a21d48e007/var/www/html
		DOCKER_HOST=
		DOCKER_TLS_VERIFY=
		DOCKER_CERT_PATH=
	Connection state: Disconnected
Status: Connecting to beta
```

Might also be worth a try stopping/starting the Mutagen daemon (you can do this by running `mutagen daemon stop` followed by `mutagen daemon start`, then re-running the `warden sync start` command and see if anything changes.

**Comment by davidalger** [comment]
@torhoehn If you have further issues and/or information here, feel free to re-open with additional details or questions regarding this. Cheers!
