### ISSUE TITLE
Error re-indexing Catalog - Magento 2.4.0 

### ISSUE THREAD

**Issue by gfilice** [davidalger/warden#248]
When I launch the indexer:reindex command, I receive everytime the following error:

Catalog Search index process unknown error:
{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [magento2_product_1_v1] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"index [magento2_product_1_v1] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}

**Comment by davidalger** [comment]
I've seen colleagues run into this error (haven't seen it personally) and it's generally due to ES putting itself into read-only mode when it encounters a disk-full error.

The following link has been shared in an internal slack with info on how to pull ES out of read-only mode: https://selleo.com/til/posts/esrgfyxjee-how-to-fix-elasticsearch-forbidden12index-read-only

Simplest solution is to simply `warden env down -v` on the project (to destroy not just containers, but also wipe out data volumes) and rebuild the project. You could do surgery to delete just the ES container and associated volume, then `warden env up` followed by re-indexing Magento, but then you're getting into complicated territory.

Also a note, if you're on a Mac, the reason many run into this is due to having insufficient space allocated to the Docker Desktop storage volume: https://docs.docker.com/docker-for-mac/space/ but it could also happen when your disk fills up even momentarily. Is it a pain? Yep, but is how ES operates to prevent data loss when running out of disk space on a production cluster.

**Comment by gfilice** [comment]
Thank you @davidalger
