### ISSUE TITLE
Dnsmasq service not working when connected to external network in ubuntu 20.04

### ISSUE THREAD

**Issue by dani97** [davidalger/warden#251]
### Description
Whenever I enable wifi or connect with ethernet, dnsmasq is not resolving warden sites. If offline dnsmasq is resolving warden sites. Tried several wifi devices seems to be not problem with wifi. Warden used to work well with my ubuntu 18.04 after 20.04 fresh install it breaks, any  config I need to change in 20.04?

#### Environment Details
Ubuntu 20.04

**Comment by sprankhub** [comment]
For me, it does not even work when I am not connected to any external network. As a workaround, you can add the necessary domains to your `/etc/hosts` file manually:

    127.0.0.1 app.your-project.test

**Comment by Skullsneeze** [comment]
I was facing this issue before as well, and for a more permanent fix (for all projects) you can add 127.0.0.1 to your list of DNS resolvers. 

On Ubuntu you can add the entry in the UI by going to your Wi-Fi/Ethernet settings, selecting the network you are connected to, going to the IPv4 tab, disable automatic DNS, and fill in `127.0.0.1,` followed by your other prefered DNS (eg. for Google DNS use `127.0.0.1, 127.0.1.1, 8.8.8.8, 8.8.4.4`.

You can also use `resolvconf` to add a permanent entry in your `/etc/resolv.conf` file, so that you won't need to update this for each network. To do this first install resolvconf `sudo apt update && sudo apt install resolvconf`. After installing edit the `/etc/resolvconf/resolv.conf.d/base` file as follows:

```
search home net
nameserver 127.0.0.1
nameserver 127.0.1.1
nameserver 8.8.8.8
nameserver 8.8.4.4
```

I believe then you just need to restart your network manager `sudo service network-manager restart`, but if that doesn't do the trick, simply do a reboot.

Hope this makes it work for you :)

**Comment by dani97** [comment]
@Skullsneeze I disabled automatic DNS and configured and now I can access every warden instance. Thanks. Didn't try the permanent fix for now but I will definitely try it out. :)

**Comment by davidalger** [comment]
I would love to see a PR with information such as the above, perhaps combined with some of the info on this page as well: https://devilbox.readthedocs.io/en/latest/howto/dns/add-custom-dns-server-on-linux.html

The next release of Warden will no longer attempt to auto-configure the DNS resolver on Linux or WSL2 both since it cannot be done reliably, and since doing so mucks with DNS settings which can sometimes be very personal.  So having documentation on how to do this, with a link to that page in the output on initial warden startup, is going to quickly become even more needed.

**Comment by Skullsneeze** [comment]
@davidalger I can create a PR with some updates for the docs this week. Will cross-reference later in this issue :)

**Comment by davidalger** [comment]
PR with info on DNS resolution has been merged and is now up on the docs site: https://docs.warden.dev/configuration/dns-resolver.html Shoutout to @Skullsneeze for making this happen!
