### ISSUE TITLE
Xdebug 3 support

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/warden#267]
Xdebug 3 has been released and makes impressive performance improvements.
Let's add support of it? https://twitter.com/derickr/status/1331613630991900674?s=21

**Comment by Den4ik** [comment]
@davidalger Unfortunately, IUS updates slower than remi and xdebug 3 still not provided there.
@ihor-sviziev Currently, I use my own builds and if you want you may try to check at fork https://github.com/magenius-team/warden/tree/main

**Comment by ihor-sviziev** [comment]
@Den4ik I believe we need to have separate image with xdebug3, so it will continue working for everyone who used xdebug 2, but with additional option to switch to xdebug 3

**Comment by Den4ik** [comment]
@ihor-sviziev good point

**Comment by Den4ik** [comment]
> Also could you explain what is the benefit of using separate fork instead of just sending Pull Request to this repo?

I use remi package repository. If @davidalger approve moving from ius to remi I'll prepare PR

**Comment by celorodovalho** [comment]
@Den4ik how can I use your fork?
I mean, I have installed on linux using homebrew, and currently I'm facing a problem regarding this issue https://youtrack.jetbrains.com/issue/WI-56500
I know I can update xdebug from remi to 2.9.7 version, however I don't know how to do that from warden source code.
So, I would like to know how can I switch to your fork at least?

**Comment by Den4ik** [comment]
@celorodovalho look at https://docs.warden.dev/installing.html#alternative-installation and use fork url instead of this repo.
You may use `PHP_XDEBUG_3=1` flag at `.env` file for using xdebug3 version

**Comment by davidalger** [comment]
@Den4ik Been debating this (transitioning to use of Remi packages) with myself for some time now actually. The PHP 7.4 packages that are available here via IUS largely were made possible by my own efforts porting the specs from Fedora to IUS and working with the IUS maintainer to publish them. A long while back (too long ago to remember when actually) I encountered 'issues' with Remi or simply preferred IUS, not sure what combination or which it was. However, since that time IUS has gone on life support primarily due to the introduction of Modules via DNS in EL 8, effectively making the need for a packaging system like IUS no longer needed. I.e. IUS will not be doing anything to support CentOS Stream/RHEL 8 etc. Another blocker to getting these in via IUS currently is that before IUS can have a package, it must make it's way into the Fedora repos, and as of this time, Fedora 34 is still running PHP 7.4, although I believe Remi (who maintains the specs for Fedora as well) will be changing that.

I'd LOVE to see what you have currently based on Remi. I know there are differences in how Remi and Fedora have PHP built, little things like specific features of GD may not be available in the packages built by Remi whereas they are in IUS (this was one I discovered when I ported PHP 7.4 into IUS to build the docker images here).

Would be happy to help make the transition, opening the door to introducing PHP 8.0 support. Since the images here are based on the generic PHP base images I've published over here: https://github.com/davidalger/docker-images-php this work would need to begin as a PR to those images. I would likely want to maintain the existing build files, adding on an `-remi` suffix to the generated tags so that both are initially available as base images, and then once the Remi based ones are known to be comparable the Remi images could become the default. Open to other's input on how to make the transition happen as well.

Given that my day job no longer relates to Magento development (not even in the PHP landscape anymore really as of this month), it will require testing efforts from others to make this happen before I would be comfortable replacing the existing 7.3 and 7.4 images with ones based on Remi as to avoid disrupting things.
