### ISSUE TITLE
Can't connect to tunnel.warden.test

### ISSUE THREAD

**Issue by erikhansen** [davidalger/warden#27]
Note: After writing most of this up, I figured out what was going on, but I'm creating and then closing this issue in case it's helpful for anyone coming after me.

I'm running macOS Mojave (10.14.6). After installing warden and using it for a few days (really like it), I had the need to setup a database GUI.

I couldn't get either PhpStorm or SequelPro to connect until I explicitly added `user` as the "SSH User":

![Sequel Pro 2019-10-24 16-49-18](https://user-images.githubusercontent.com/129031/67528114-48d8f100-f67e-11e9-8b95-c0cffd68d910.jpg)

Likewise, I this command works in Terminal:
```
ssh user@tunnel.warden.test
Welcome to the Warden SSH tunnel!
```

But this doesn't:
```
ssh tunnel.warden.test
ehansen@127.0.0.1's password:
```
I realized the reason why this was happening (thanks to the `ssh -vvv` flag):

1. Warden adds this to the `/etc/ssh/ssh_config` file:
   
       ## WARDEN START ##
       Host tunnel.warden.test
         HostName 127.0.0.1
         User user
         Port 2222
         IdentityFile ~/.warden/tunnel/ssh_key
       ## WARDEN END ##
   
2. However at the bottom of my `~/.ssh/config` file, I had this entry:
   
       Host *
           User ehansen
   
3. Due to the load order of the config files, my configuration was overriding the Warden configuration when I ran `ssh tunnel.warden.test`: SSH was attempting to use my `ehansen` username (it did use the correct Port and IdentityFile).

My solution was to remove the entry from my `~/.ssh/config` file.

**Comment by davidalger** [comment]
@erikhansen Thanks for sharing the details and related solution. It may help somebody else in the future. Cheers!

**Comment by Elamurugan-Nallathambi** [comment]
In my case for some reason this entry 

```
## WARDEN START ##
Host tunnel.warden.test
  HostName 127.0.0.1
  User user
  Port 2222
  IdentityFile ~/.warden/tunnel/ssh_key
## WARDEN END ##
```


not added in `/etc/ssh/ssh_config` and once I added the DB connection worked.

**Comment by davidalger** [comment]
@Elamurugan-Nallathambi 
This entry is known to be cleared from that file when upgrading to macOS Catalina. Perhaps something like that did it. Should it turn up missing a simple `warden install` generally resolves the issue.

**Comment by Elamurugan-Nallathambi** [comment]
@davidalger Thanks for updating quickly, yesterday I did ran the upgrade and now it makes sense.

**Comment by redo-interactive** [comment]
@davidalger lately I have similar problem with tunnel.warden.test on macos. And I'm not sure if it result of some kind of update on my system. Because it was working without any problems. 

And now when I try to connect to tunnel via console it says that: 
ssh user@tunnel.warden.test
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:6yOQF7Ki1gGYQa4DS5UJCGAETr0e6MlKWzFY/O32C/c.
Please contact your system administrator.
Add correct host key in /Users/redo/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/redo/.ssh/known_hosts:7
ECDSA host key for [127.0.0.1]:2222 has changed and you have requested strict checking.
Host key verification failed.

I have tried to remove line no. 7 from know-hosts, but after reconnecting to tunnel.warden.test it gives me this result:
ssh user@tunnel.warden.test
The authenticity of host '[127.0.0.1]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA key fingerprint is SHA256:6yOQF7Ki1gGYQa4DS5UJCGAETr0e6MlKWzFY/O32C/c.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
user@127.0.0.1: Permission denied (publickey,keyboard-interactive).

From phpstorm I'm not able to connect to databases, it says that authentication is denied. 

You think that you could give me some idea what is wrong with my settings?

**Comment by Smalto22** [comment]
I am having the same issue as @redo-interactive 
I have just installed warden on my mac (running Big Sur) and when I run `ssh user@tunnel.warden.test`, I get the following error:
user@127.0.0.1: Permission denied (publickey,keyboard-interactive).

Both IntelliJ and TablePlus are failing to connect.

Any idea what could be the issue?

**Comment by Smalto22** [comment]
This worked for me:
https://github.com/davidalger/warden/issues/260#issuecomment-722355346

**Comment by redo-interactive** [comment]
@Smalto22 it worked :), thanks.

**Comment by conflicker** [comment]
Thank you @Smalto22!

**Comment by 0-Sony** [comment]
Hi guys, I encountered the same issue today. I already had this issue the first time that i tried warden and I resolved it by following #260 .

But unfortunately it doesn't help this time. After some investigation, I fixed the issue by changing the option in my **Sequel Ace**. I explicitly gave the ssh config file that I want to use.

In that config file there is the warden config
```
## WARDEN START ##
Host tunnel.warden.test
    HostName 127.0.0.1
    User user
    Port 2222
    IdentityFile ~/.warden/tunnel/ssh_key
## WARDEN END ## 
```

<img width="1223" alt="Screenshot 2021-04-06 at 11 25 19" src="https://user-images.githubusercontent.com/7865528/113689638-75da6180-96c2-11eb-8746-f67f73d894a2.png">

Hope it helps. My fix is quite specific but hope it could give you a track.

**Comment by EduardoChacal** [comment]
phpStorm in mint using.

ssh Config:
![image](https://user-images.githubusercontent.com/6317799/209203823-9ab8fc7a-46e5-407b-bc44-ea31294a95bd.png)

data source:
![image](https://user-images.githubusercontent.com/6317799/209204026-1c7de5f4-c661-49e5-b1f1-107827998d01.png)

**Comment by AnimNyan** [comment]
> phpStorm in mint using.
> 
> ssh Config: ![image](https://user-images.githubusercontent.com/6317799/209203823-9ab8fc7a-46e5-407b-bc44-ea31294a95bd.png)
> 
> data source: ![image](https://user-images.githubusercontent.com/6317799/209204026-1c7de5f4-c661-49e5-b1f1-107827998d01.png)

I'm getting an error from using the exact same configuration I'm using WSL2 with warden for magento 2.4.6.

The error I'm getting is in PHPStorm when I'm setting up the SSH configuration to connect to the database from warden. I'm getting a Connection to user@tunnel.warden.test:2222 Cannot connect to remote host: host not found 

My settings in PHPStorm for the SSH Configuration is Host: tunnel.warden.test , Port: 2222, Username: user, Private key file: \\wsl$\Ubuntu\home\<myusername>\.warden\tunnel\ssh_key and Parse config file ~/.ssh/config is turned on.

However, when I try the command:
```
ssh user@tunnel.warden.test
Welcome to the Warden SSH tunnel container!

This tunnel container is used only for forwarding TCP
connections, generally to port 3306 of db containers
and is not typically used with an interactive shell.

```

I've also checked in my /etc/ssh/ssh_config and see this entry which I see was mentioned above:
```
## WARDEN START ##
Host tunnel.warden.test
HostName 127.0.0.1
User user
Port 2222
IdentityFile ~/.warden/tunnel/ssh_key
## WARDEN END ##
```

It works. I looked at the solution here: https://github.com/wardenenv/warden/issues/27#issue-512203247 by @erikhansen but I don't see this file ~/.ssh/config in my Ubuntu WSL 2 machine.

I'm seeing this:
```
cat ~/.ssh/config
cat: /home/seabrook/.ssh/config: No such file or directory
```

So I don't have anything to delete I'm just very confused because ssh works fine but the ssh configuration to my WSL 2 ubuntu vm running mysql does not work.

**Comment by tonybenny2020** [comment]
Hi All,
The permanent  solution for this issue is to update your JDBC drivers for MariaDB if you are using MariaDB .This can be achieved by Going to Dbeaver->Database->Driver Manager and then Double click on MariaDB in the list which will open a dialog window with tabs including Settings, Libraries etc, go to the Libraries tab and then click on Download/Update in the right-hand side. Then please download the update by checking the message 'MariaDB driver files are missing' in the dialog box. Don't forget to tick the Force download/overwrite checkbox, Click on the download botton and you will get the latest update of JDBC driver. Restart the Dbeaver and Just delete your DB connection in the Dbeaver. and re add the DB connection with the warden SSH details and connection setting by deleting the older connection settings. Click on the test connection it will work fine. Refer the screenshots for easier fix.
![1](https://github.com/user-attachments/assets/be5c51c4-e248-4980-ad56-edb49d2a1262)
![2](https://github.com/user-attachments/assets/9e508b23-50e5-4a61-aee5-c477e7f09283)
![3](https://github.com/user-attachments/assets/34cdb37f-624e-467a-b382-6369a23f7672)
![4](https://github.com/user-attachments/assets/8b76a2ee-3a66-41da-b385-0fb427a23a2a)
![Screenshot 2024-08-05 091138](https://github.com/user-attachments/assets/05ff77fc-cafe-4925-9b5b-7c10a802b813)
