### ISSUE TITLE
Elasticsearch 6.8 Container not running

### ISSUE THREAD

**Issue by michi-z** [davidalger/warden#275]
Hello, i tried to work with the elasticsearch image 6.8 but the container is always on 'Exit 1' after i startet my magento 2 environment. Do i have to change same other configuration as in the environment .env file?

**Comment by davidalger** [comment]
Have you checked the container logs? Also worth mentioning if you change the ES version after it has previously been started, your best bet is to blow things away (or otherwise remove the esdata volume) and then restart the ES container as Elasticsearch isn't always capable of starting with the data set from a newer/older version of ES/

**Comment by michi-z** [comment]
Thx for the advice. I will try that.
