### ISSUE TITLE
Replace part of images with original from docker hub

### ISSUE THREAD

**Issue by Den4ik** [davidalger/warden#303]
@davidalger I think it would be good to replace some images like redis, mariadb, mysql with original images from hub.
These images don't require any customizations. Currently, we need to wait for warden update to support new versions.

**Comment by adam-paterson** [comment]
Can you not override them with `.warden/warden-env.yml`?

**Comment by davidalger** [comment]
The ability to override is there are @adam-paterson pointed out. It was by-design that the images used by Warden switched to reference those in the wardenenv account on Docker Hub (originally, I think all 3 of these pointed at the original images) as there may be a need for an entrypoint script for these in the future to support features and so this keeps the door open for that. An example would be having the redis container _not_ persist data on disk, something I've given thought to due to the better DevEx where restarting the container will flush what's in it, resetting it (something I've seen folks trip over, not realizing the redis container by default writes to disk on a volume, that's not re-created even if they delete and re-create the container)

Perhaps it would be useful to update the CI routines to fetch the major versions available, and build/push an image for each minor version available to eliminate the manual steps.
