### ISSUE TITLE
Mount local ssh keys

### ISSUE THREAD

**Issue by wpoortman** [davidalger/warden#318]
- [x] _For local development purposes only_

### Issue
I need to pull in some private packages who can only be authenticated by the public key. Now I need to generate and register these new unique keys every single time I spawn a new environment.

### Solution that didn't work
```
x-volumes: &volumes
  - ...
  - ~/.ssh/:/root/.ssh/
```

### Question
Would love to hear suggestions how to mount my local keys into the enviroment.

**Comment by Skullsneeze** [comment]
Seems to be a permission issue on the SSH auth socket.

After starting up my env, and hopping into the php-fpm container I run `ssh-add -l` and get a permission denied error.
Seems to be caused by the socket being mounted as a file owned by root:root, with insufficient permissions

### Temp fix:
Open an interactive bash session in your php-fpm container as root user
`docker container exec -u 0 -it [YOUR_CONTAINER] bash`

Update permissions for the socket:
`chmod 666 /run/host-services/ssh-auth.sock`

Afterwards, exit out of the container, and hop back in as a regular user:
`warden shell`

Then try to see if your ssh key is listed:
`ssh-add -l`


My guess is that at some point this should be fixed on the entrypoint level. But this might help you and other out for now :)

**Comment by springerin** [comment]
The issue @Skullsneeze i suppose is referring to is #331
Based on that issue my workaround was to put in the folder .warden the file .warden-env.yml with the following

`version: "3.5"
services:
  php-fpm:
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock`

**Comment by ihor-sviziev** [comment]
@wpoortman, what OS are you using? If Linux - does the issue reproducing on the 0.10.2 version?

**Comment by wpoortman** [comment]
@ihor-sviziev without the ideas mentioned above, it seems 0.10.2 has the same issue when running on Linux

**Comment by alinalexandru** [comment]
Please make sure that the ssh-agent is running and you have the keys added into it.
Run `ssh-add -L`. If no entities are added, please run `ssh-add path-to-key`

**Comment by wpoortman** [comment]
So after putting it aside for a while, I've picked up where I left off. Still, all the options above ain't working. I'm constantly getting the errors `Could not open a connection to your authentication agent.` with sudo and `The agent has no identities.` without.

**Comment by Igloczek** [comment]
Running `ssh-add ~/.ssh/id_rsa` on host, fixed the problem for me.

So basically, if your host prints nothing from `ssh-add -L`, it's not a Warden issue.
