### ISSUE TITLE
Traefic Livereload route gets lower priority than M2 website

### ISSUE THREAD

**Issue by alinalexandru** [davidalger/warden#335]
Can't find the pattern, but for some projects, the livereload route gets lower priority than M2 website.

As a quick fix, I am overwriting live reload priority at project level.
```
- traefik.http.routers.${WARDEN_ENV_NAME}-livereload.priority=3
```

Is there a reason why in default config the live reload doesn't have a higher priority?

https://github.com/davidalger/warden/blob/develop/environments/magento2/magento2.base.yml#L12

**Comment by davidalger** [comment]
@alinalexandru Could the difference in the projects that do vs don't work be the use of Varnish? The Nginx priority is at 2 so that Traefik will route to it correctly instead of Varnish in the event `WARDEN_VARNISH=0` but the varnish container happens to still be running. When that was bumped (in https://github.com/davidalger/warden/commit/fc8c5a46d25b722054ab302e14fa04b56525d302#diff-7c33b3770d786e3b5628dedbf9531c503054b547e33f1e4f048a354382399a36 while doing a major refactor) it's possible no-one has caught it until now (I always used Varnish, as did most of my colleagues for example)

Priority is typically calculated by Traefik based on length of hostname https://doc.traefik.io/traefik/routing/routers/#priority which doesn't work so well for these scenarios, hence the static priority numbers.

I haven't tested this, but I'm guessing what happens (when Varnish is disabled) is the Nginx router and Live Reload router both have the same priority, and both will match the requests for Live Reload resulting in a sort of round robin and thus lack of reliability. So I think you're spot on with the priority here needing to be incremented.

Would you mind submitting a PR with this change?

**Comment by alinalexandru** [comment]
Yes, varnish is not used and what you are saying seems plausible 
I will make a PR with priority increased.

**Comment by alinalexandru** [comment]
I would even suggest to have 

```
varnish.priority=10
nginx.priority=20
livereload.priority=30
```

In this way, you let space for other posibile services to be added in between.
What to you think?

**Comment by davidalger** [comment]
@alinalexandru Thanks for submitting the PR. I'll get it merged in as soon as I can.

I'm hesitant to use the 10/20/30 for priority only because of how Traefik auto-calculates them by default when unspecified. It's based on the length of the hostname. So for example, having the livereload priority at 30 could result in it breaking if someone adds a container with a generic route with a domain short enough to have a lower priority value. Let's just go with setting it at 3 for now.
