### ISSUE TITLE
xDebug  not activated

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#34]
Followed the steps like it stated [here](https://github.com/davidalger/warden#warden-usage-information) and here is the screenshot of how it looks like

![xdebug-settings](https://user-images.githubusercontent.com/54947876/68510776-62fbfd00-0242-11ea-98f3-6cc15f884fb1.png)

From chrome after enabling the debugging profile through xdebug helper chrome extension I can see the Cookie like below

![cookie](https://user-images.githubusercontent.com/54947876/68510253-fa605080-0240-11ea-8037-6eba34ba823c.png)

Environment:
![os](https://user-images.githubusercontent.com/54947876/68510360-54611600-0241-11ea-9f5b-af65974d4956.png)

All containers and every  other service is working,
![docker_containers](https://user-images.githubusercontent.com/54947876/68510748-4c55a600-0242-11ea-8681-fb6ee290ece9.png)

But not able to use xdebug with PHPStorm
![phpstorm](https://user-images.githubusercontent.com/54947876/68510536-ce919a80-0241-11ea-8898-fb3badf6f32e.png)

This is something am newly trying with docker based xdebug in phpstorm, the valet+ xdebug works ok with phpstorm.

**Comment by davidalger** [comment]
Based on these screenshots, it appears to me everything is configured correctly at a glance. Could you check a few things here?

a) Verify requests are hitting the `php-debug` container (as they should be based on the cookie noted above) by running the following and then making a few requests from your browser. If it's routing correctly, you should see logs from `php-debug_1` in the output vs the non-debug logged requests hitting `php-fpm_1`

```
warden env logs --tail 0 -f nginx php-fpm php-debug
```

b) Could you make sure nothing (other than phpstorm) is listening on port 9000 on your host machine? If PHP Storm is not listening on this port, that is likely where the problem is, and could be caused by something as simple or as complicated as having php-fpm running on the host OS conflicting with PHP Storm when you "Start Listening for PHP Debug Connections" in PHP torm. An easy way to check this would be this:

```
davidalger:03:37 PM:~$ sudo lsof -i -n -P | grep LISTEN | grep 9000
phpstorm  73667     davidalger  427u  IPv4 0xe64878cb81110879      0t0    TCP *:9000 (LISTEN)
```

c) Update PHP Storm to the latest version. I'm not sure what version it was that wasn't working for me, but I had this seeming inability to get PHP Storm debugging working on one of my Macs until I updated to the latest PHP Storm release, despite it working fine on that laptop from VS Code. Updating PHP Storm resolved it for me, and I'm currently running PHP Storm 2019.2.4 at this moment (with a working debug configuration)

I'm running macOS Catalina currently and debugging without an issue, so I think we can rule the OS version out this time. Appreciate you including that detail though.

**Comment by Elamurugan-Nallathambi** [comment]
@davidalger 

I ran these tests 

a) php-debug gets the requests
![Screen Shot 2019-11-16 at 2 35 09 PM](https://user-images.githubusercontent.com/54947876/68998278-657fd780-087e-11ea-9e0c-b9dc06ce3bb5.png)
b) 9000 port being used by multiple php-fpm process and phpstorm as well [Not sure why or how this is happening]
![Screen Shot 2019-11-16 at 2 37 49 PM](https://user-images.githubusercontent.com/54947876/68998305-ad066380-087e-11ea-9b25-c9f7ddc5cef0.png)

Even if i kill the php-fpm processes, it automatically starts again and this happens regardless of warden env up or stopped. I made sure valet or any other docker containers related to php or php-fpm is not running/not active and still not sure how these three services always running

c) I did updated phpstorm to PhpStorm 2019.2.5, Build #PS-192.7142.51, built on November 13, 2019

Samething with VS Code xdebug setup also, there also I couldn't make this working. Seems like I messed up my environment again with multiple experiments.

**Comment by Elamurugan-Nallathambi** [comment]
@davidalger  your response for very helpful debugging the issue, thank you for directing me in right direction. 

After above investigation I just ran `brew services ls` and I found still the other php versions was showing as `started` and then after I ran `brew services stop php@[version]` then the other 9000 port listening services was gone and then the xdebug started working.
