### ISSUE TITLE
Using MySQL 8 with magento2

### ISSUE THREAD

**Issue by sebastian-ehrling** [davidalger/warden#354]
Hi @davidalger 

with magento2 and your mysql8 image (docker.io/wardenenv/mysql:8.0) there is an error when importing existing magento databases.
The following setting resolves the problem. Is it possible to set this setting by default in your mysql8 image?

[mysqld]
log_bin_trust_function_creators=ON

**Comment by sebastian-ehrling** [comment]
My current workaround:
warden-env.yml
    db:
        image: docker.io/wardenenv/mysql:8.0
        volumes:
            - ./.warden/mysql/logbintrust.cnf:/etc/mysql/conf.d/logbintrust.cnf:cached

logbintrust.cnf
[mysqld]
log_bin_trust_function_creators=ON

**Comment by sebastian-ehrling** [comment]
PR: https://github.com/davidalger/warden/pull/384/files

**Comment by davidalger** [comment]
@sebastian-ehrling Please comments on #403. This issue was run into because MySQL 8.0 changed the defaults for binary logging, and binary logging is incompatible with Magento 2 without that  `log_bin_trust_function_creators` setting you noted (I've used this many times on production clusters). Instead of just adding `log_bin_trust_function_creators=ON` however, I'm going to disable bin logging on the MySQL 8 image, as it's not really needed on a single db instance for local development, and disabling it will reduce overhead that will do nothing more than slow down local developer machines.

**Comment by sebastian-ehrling** [comment]
ok great!
