### ISSUE TITLE
swoole support

### ISSUE THREAD

**Issue by emreakay** [davidalger/warden#371]
hi,

will you bring swoole support for laravel octane?

Thanks

**Comment by davidalger** [comment]
@emreakay What would this entail, and are you willing to submit PRs, document them, etc? Tbh I'm not sure why one would use Swoole, nor how it would fit into Warden. The only thing I know about it is from a basic web search, skimming the project's README, where claims seem to boil down to it's faster than FPM because PHP has to load files on every request (something that is NOT true when PHP-FPM is used with OpCache properly enabled and configured). The benchmarks don't even make a mention of Opcache, or any other PHP configuration for that matter, making them impossible to reproduce. Value of Swoole aside, what advantage would it have to users of Warden? What would supporting it involve?

**Comment by emreakay** [comment]
i want to use warden on production for my alaravel project and i want to run my project with swoole and octane.

**Comment by MagePsycho** [comment]
+1 for Swoole support in Warden.
Swoole seems to solve many performance problems of PHP and Adobe commerce leveraging Swoole for GraphQL server also proves that.
