### ISSUE TITLE
Feature request/support for Windows Containers

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#38]
@davidalger  In one of the current M2 project some of our team has to work on Windows and they don't have way for ubuntu or not even in WSL. So I tried gathering "davidalger/warden" magento images and created environment for Magento 2 as attached here. 

[m2_env.zip](https://github.com/davidalger/warden/files/3855253/m2_env.zip)

The issues it's having
- It's very slow [Even in same ubuntu machine warden containers are really fast but this containers are very slow] => Are you able to spot what should be added/changed in this to make it work faster just with this images?
- How can I add SSL certificates or enable way for https to these local development environment

This will be really great option if the same lib. can work in Windows also

**Comment by davidalger** [comment]
@Elamurugan-Nallathambi It's a curious idea, but I'm not sure supporting non-WSL installs on Windows is something that's even feasible here. I'm not a Windows guy, but I'm pretty sure you need WSL to run bash scripts, and that is largely the makeup of this tool :) 

Not being a Windows guy, I'm not really sure what options you have without using WSL to sign SSL certs on a Windows only environment. As far as docker containers for handling them, feel free to reference https://github.com/davidalger/warden/blob/master/docker/docker-compose.yml which is the definition for the containers Warden runs to route requests via Traefik. They may come in useful.

As far as performance goes, it's my understanding that Docker for Windows suffers similar performance issues as on macOS when mounting directories from the host into the containers. This is because Docker can't really run containers natively on a Windows or macOS host (it runs them in a VM in both cases). So you'll be wanting to look into Mutagen as is done for `darwin` environments on macOS. On `darwin` environments, `pub/media` is mounted, and the rest is sycned into the container by mutagen session started via `warden sync start` (something that's not used on Linux). These references may be helpful:

https://github.com/davidalger/warden/blob/master/environments/magento2.darwin.yml
https://github.com/davidalger/warden/blob/master/environments/magento2.mutagen.toml

If someone would like to put in the effort to tackle supporting WSL and closing whatever gap there may be installing Warden on Windows in context of WSL, I'd be open to merging PRs to that effect. I have no Windows setup around to test on however (and not much desire to do this myself for the time being). I know that @adexandros at least took a stab at installing Warden on WSL at one point, but not sure what the results were, although I do note you're indicating the immediate issue at hand WSL wouldn't work.

**Comment by davidalger** [comment]
Closing as I have no intent (nor the time) to provide support for Warden on Windows currently. If a contributor would like to make this happen, it may be re-opened.
