### ISSUE TITLE
Mutagen: Error: unable to connect to daemon: connection timed out

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#418]
```
➜ warden env up

Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "magento243_default" with the default driver
Creating volume "magento243_bashhistory" with default driver
Creating volume "magento243_sshdirectory" with default driver
Creating volume "magento243_dbdata" with default driver
Creating volume "magento243_esdata" with default driver
Creating volume "magento243_redis" with default driver
Creating volume "magento243_appdata" with default driver
Creating magento243_elasticsearch_1    ... done
Creating magento243_db_1               ... done
Creating magento243_elasticsearch-hq_1 ... done
Creating magento243_redis_1            ... done
Creating magento243_php-fpm_1          ... done
Creating magento243_nginx_1            ... done
Creating magento243_php-debug_1        ... done
Connecting traefik to magento243_default network
Connecting tunnel to magento243_default network
Connecting mailhog to magento243_default network
Docker Compose is now in the Docker CLI, try `docker compose up`

Starting magento243_elasticsearch_1    ... done
Starting magento243_elasticsearch-hq_1 ... done
Starting magento243_db_1               ... done
Starting magento243_redis_1            ... done
Recreating magento243_php-fpm_1        ... done
Recreating magento243_php-debug_1      ... done
Recreating magento243_nginx_1          ... done
Attempting to start Mutagen daemon...
Error: unable to connect to daemon: connection timed out (is the daemon running?)
ERROR: Command `mutagen sync "${WARDEN_PARAMS[@]}" "${@}" --label-selector "warden-sync=${WARDEN_ENV_NAME}"` at /usr/local/Cellar/warden/0.12.0/commands/sync.cmd:72 failed with exit code 1
Attempting to start Mutagen daemon...
Error: unable to connect to daemon: connection timed out (is the daemon running?)
ERROR: Command `mutagen sync "${WARDEN_PARAMS[@]}" "${@}" --label-selector "warden-sync=${WARDEN_ENV_NAME}"` at /usr/local/Cellar/warden/0.12.0/commands/sync.cmd:72 failed with exit code 1
Attempting to start Mutagen daemon...
Error: unable to connect to daemon: connection timed out (is the daemon running?)
ERROR: Command `mutagen sync terminate --label-selector "warden-sync=${WARDEN_ENV_NAME}"` at /usr/local/Cellar/warden/0.12.0/commands/sync.cmd:48 failed with exit code 1
```

When I try to start the project environment, I getting the error as:   
> ERROR: Command `mutagen sync "${WARDEN_PARAMS[@]}" "${@}" --label-selector "warden-sync=${WARDEN_ENV_NAME}"` at /usr/local/Cellar/warden/0.12.0/commands/sync.cmd:72 failed with exit code 1

**Comment by MagePsycho** [comment]
With the restart, it fixed the issue.

**Comment by diazwatson** [comment]
Restarting my laptop fixed the issue for me.
The issue was probably caused by a `brew update` I did during the day. 🤔

**Comment by bap14** [comment]
@diazwatson It's easy to miss, but there is a message when Mutagen gets updated that you need to restart the Mutagen daemon.

```
$ mutagen daemon stop
$ mutagen daemon start
```

This is also called out specifically in the official Mutagen [documentation about upgrading](https://mutagen.io/documentation/introduction/daemon#upgrading).

**Comment by eWings-agency** [comment]
It seems the issue is not yet 100% solved, when I use @bap14  commands I get: 

` ✘  ~/dev/INT   master ±✚  mutagen daemon stop
Error: unable to connect to daemon: connection timed out (is the daemon running?)
 ✘  ~/dev/INT   master ±✚  mutagen daemon start
 ~/dev/INT   master ±✚  warden env up       
Connecting traefik to int_default network
Connecting tunnel to int_default network
Connecting mailhog to int_default network
WARN[0000] Found orphan containers ([int-elasticsearch-hq-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 8/0
 ✔ Container int-rabbitmq-1       Running                                                                                                                                                                                                                                         0.0s 
 ✔ Container int-redis-1          Running                                                                                                                                                                                                                                         0.0s 
 ✔ Container int-db-1             Running                                                                                                                                                                                                                                         0.0s 
 ✔ Container int-elasticsearch-1  Running                                                                                                                                                                                                                                         0.0s 
 ✔ Container int-php-fpm-1        Running                                                                                                                                                                                                                                         0.0s 
 ✔ Container int-php-debug-1      Running                                                                                                                                                                                                                                         0.0s 
 ✔ Container int-nginx-1          Running                                                                                                                                                                                                                                         0.0s 
 ✔ Container int-varnish-1        Running                                                                                                                                                                                                                                         0.0s 
Attempting to start Mutagen daemon...                                           
Error: unable to connect to daemon: connection timed out (is the daemon running?)
ERROR: Command `mutagen sync "${WARDEN_PARAMS[@]}" "${@}" --label-selector "warden-sync=${WARDEN_ENV_NAME}"` at /opt/homebrew/Cellar/warden/0.14.1/commands/sync.cmd:53 failed with exit code 1
Attempting to start Mutagen daemon...                                           
Error: unable to connect to daemon: connection timed out (is the daemon running?)
ERROR: Command `mutagen sync "${WARDEN_PARAMS[@]}" "${@}" --label-selector "warden-sync=${WARDEN_ENV_NAME}"` at /opt/homebrew/Cellar/warden/0.14.1/commands/sync.cmd:53 failed with exit code 1
Attempting to start Mutagen daemon...                                           
Error: unable to connect to daemon: connection timed out (is the daemon running?)
ERROR: Command `mutagen sync terminate --label-selector "warden-sync=${WARDEN_ENV_NAME}"` at /opt/homebrew/Cellar/warden/0.14.1/commands/sync.cmd:53 failed with exit code 1
 ✘  ~/dev/INT   master ±✚  
`

**Comment by diazwatson** [comment]
@eWings-agency Have you tried restarting your computer?

**Comment by gmiguelete** [comment]
> [@diazwatson](https://github.com/diazwatson) It's easy to miss, but there is a message when Mutagen gets updated that you need to restart the Mutagen daemon.
> 
> ```
> $ mutagen daemon stop
> $ mutagen daemon start
> ```
> 
> This is also called out specifically in the official Mutagen [documentation about upgrading](https://mutagen.io/documentation/introduction/daemon#upgrading).

works for me!
