### ISSUE TITLE
Point public url to the warden project

### ISSUE THREAD

**Issue by amir-prince** [davidalger/warden#421]
Hi,
I have installed some warden project in a remote server, this server has public and private IP, I want to know if it's possible to link that public IP to the project, for example when I enter mynewproject.com (public IP), this will redirect to my project ?

Thanks

**Comment by tdgroot** [comment]
You could configure Warden to bind on `0.0.0.0:443/80` instead of default `127.0.0.1:443/80`, so it is reachable from the outside.

Then you need to either change Warden a bit, so that your general server hostname is used instead of `.test` TLD, for example `yourwardenserver.com`.

Then you create environments with hostname `magentoenv.yourwardenserver.com`.

Another option is to not change Warden and add traefik labels for your environment by providing a `.warden/warden-env.yml`.

Now the only missing thing is SSL certs, since you need valid licenses. My advice would be to generate a Let's Encrypt wildcard for `*.yourwardenserver.com` certificate (which works with DNS TXT record challenges). 

Once you have the SSL certificate, you can load it up to traefik (not sure how exactly, but you can check out Warden as an example) and start using your public Warden environment!

**Comment by amir-prince** [comment]
Thank you @tdgroot for your reply,

Do you know in which file I have to update `0.0.0.0:443/80` instead of default `127.0.0.1:443/80`?
to replace .test, I'll update it in `.env` file: `TRAEFIK_DOMAIN=yourwardenserver.com` right ?

Sorry but what do you mean by "Then you create environments with hostname magentoenv.yourwardenserver.com" ?

Lets take this example:
```
my hostname:  yourwardenserver.com
project path: /var/www/magento_project

```
About the SSL, I dont need a wildcard domaine, just `www.yourwardenserver.com` I already have the SSL certs :)

**Comment by davidalger** [comment]
> Do you know in which file I have to update 0.0.0.0:443/80 instead of default 127.0.0.1:443/80?

See the notes on `TRAEFIK_LISTEN` found here: https://docs.warden.dev/services.html

Be forewarned that by doing this, you'll be exposing not only the site, but also the global services such as Mailhog, RabbitMQ, Portainer, etc and that may pose a significant security risk should anyone discover they can access administrative pages that will be available publicly via the same Traefik endpoint.

**Comment by amir-prince** [comment]
Thank you @davidalger 

About the security side, if I protect the different env (Mailhog...) by an htaccess, what do you think? in which directory I could add these htaccess?

**Comment by grzegorzrzeznikiewicz** [comment]
Hello,
I have a problem to setup warden on my custom domain. I use domain, let's say mydomain.com. Following this topic I created ~/.warden/.env file with content:
```
TRAEFIK_LISTEN=0.0.0.0:443
WARDEN_SERVICE_DOMAIN=mydomain.com
```

I created Let's Encrypt for this domain some time ago, but I used `warden sign-certificate mydomain.com` to be sure is set correctly. Then I ran `warden svc up`, but in my browser (chrome) after putting mydomain.com I have `404 page not found`. Page/service https://traefik.mydomain.com/ is not available. Same for other services. I'm sure I missed something during this configuration, but I have no idea what exactly. Could you someone help me?

**Comment by navarr** [comment]
@grzegorzrzeznikiewicz Warden being publicly accessible is not officially supported.  I do recommend you post in the Help forum, though, rather than a closed issue: https://github.com/orgs/wardenenv/discussions/categories/help-support

**Comment by navarr** [comment]
@grzegorzrzeznikiewicz Warden being publicly accessible is not officially supported.  I do recommend you post in the Help forum, though, rather than a closed issue: https://github.com/orgs/wardenenv/discussions/categories/help-support
