### ISSUE TITLE
Unable to boot Magento 2 warden environments

### ISSUE THREAD

**Issue by DanCarlyon** [davidalger/warden#443]
I'm getting the following error and so far unable to find the cause of it, anyone seen it before or know the fix?

```
Error: create failed: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to install agent: unable to invoke agent installation: exit status 1
ERROR: Command `mutagen sync create -c "${MUTAGEN_SYNC_FILE}" --label "warden-sync=${WARDEN_ENV_NAME}" --ignore "${WARDEN_SYNC_IGNORE:-}" "${WARDEN_ENV_PATH}${WARDEN_WEB_ROOT:-}" "docker://$(warden env ps -q php-fpm)/var/www/html"` at /usr/local/Cellar/warden/0.12.0/commands/sync.cmd:45 failed with exit code 1
make: *** [start] Error 1
```

**Comment by rbouma** [comment]
Do you have disabled Composer V2 in your Docker settings?

**Comment by DanCarlyon** [comment]
I don't believe so

**Comment by rbouma** [comment]
I had similar issue.
Goto Docker -> Preferences -> uncheck Use Docker Compose V2.
Then apply and restart.

After restart docker restart warden envoirment:
warden svc down && warden svc up.

then on project environment the same:
warden env down && warden env up.

let me know if this fixed your issue.

I am on Intel Mac btw.

**Comment by DanCarlyon** [comment]
Just had a look in docker, looks like it was already disabled
![image](https://user-images.githubusercontent.com/4364774/140497259-d894a30a-9229-494b-ba3b-693d6cdc6440.png)

I'm also on intel mac

**Comment by rbouma** [comment]
Looks like the synchronisation between local file system and docker can't find the php-fpm container for you project.

can you run 'docker ps' and check if your in the names column if %WARDEN_ENV_NAME%_php-fpm_1 exists?

maybe it was killed by mac because docker has not enough allocation for Memory.

I have set my Memory limit on 12.00GB in docker settings under resources tab -> advanced -> Memory

Maybe thats the issue.

**Comment by DanCarlyon** [comment]
Looks like the cause was my docker image size wasn't big enough 🤦
