### ISSUE TITLE
`ps` command missing with the latest Magento PHP images

### ISSUE THREAD

**Issue by lbajsarowicz** [davidalger/warden#506]
After pulling the latest Docker images, Magento Integration Tests are not passing due to the missing `ps` package.

**Comment by davidalger** [comment]
@lbajsarowicz Seems the `ps` command is no longer included in the base images by default. Might have happened in January when the base was changed from `centos:8` to `quay.io/centos/centos:stream8`, or RedHet _might_ have stopped including the `procps` package in container images by default some time since then.

Added the `procps` package to base php images (https://github.com/davidalger/docker-images-php/commit/14e912cd90f8bc674e2cb27f3ab58035d7980dbb) and warden php-fpm images are rebuilding now: https://github.com/davidalger/warden/actions/runs/2075459007

**Comment by davidalger** [comment]
Should have `ps` if you re-pull the images now.
