### ISSUE TITLE
`www-data`'s UID = 33 with the latest PHP images

### ISSUE THREAD

**Issue by lbajsarowicz** [davidalger/warden#515]
During setting up environment for a project, I noticed that the latest PHP images have UID and GID for the `www-data` set to `33` instead of `1000` which causes some extra issues.

Short term workaround is 
```
sudo groupmod -g 1000 www-data
sudo usermod -u 1000 www-data
```

**Comment by ihor-sviziev** [comment]
@lbajsarowicz,
Could you please provide the issues you're facing?
I use Debian-based images from @drpayyne, where the user id is 33, but I don't see any issues with my Mac.

**Comment by davidalger** [comment]
@ihor-sviziev Different uid/gid values don't usually cause issues on Mac hosts due to things working differently with the Docker Desktop VM containers run in. It becomes a problem on Linux since the files are mounted natively into the containers, and uid/gid carries over and must match between the host and what's running in the container (which won't have access to files which have a mismatched uid/gid within the container).

Default uid/gid for first user created on Linux is 1000, on MacOS it's 501, but since it only really matters on Linux the uid/gid is set to 1000 in the Warden php images.

**Comment by bmelman** [comment]
uid and gid should be configurable, they should be the user's uid/gid so there are no filesystem bind mount issues. Default uid for first user created on linux is 1000 but for new users it increments.
