### ISSUE TITLE
Call API on local machine

### ISSUE THREAD

**Issue by francesco-di-marcantonio** [davidalger/warden#528]
Hi there, i have got a magento2 installation in warden. From a controller i need to call a local rest api server on 127.0.0.1:8000

I changed the etc/hosts with ip port but when i try to ping it or to curl it it gives me 

curl: (7) Failed to connect to domain.XX port 8000: Connection refused

How can i configure the environment to enable this port and send request from m2 to rest server?

**Comment by flpandre** [comment]
Hi, I had to do something similar recently.

Instead of `127.0.0.1` you can try `host.docker.internal` or `ping host.docker.internal` for getting the proper IP. That will direct the requisition from your VM to your host. I am on mac, there are a few more content on how to get the proper IP here: https://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container if you are on Linux.
