### ISSUE TITLE
Accessing Warden sites from Windows VirtualBox VMs

### ISSUE THREAD

**Issue by erikhansen** [davidalger/warden#55]
I'd like to test a local app.example.test site using a Windows VM running in VirtualBox.

I've added this entry to the `c:\Windows\System32\Drivers\etc\hosts` file:

```
127.0.0.1 app.example.test
```

However I'm not able to get the site to load within the VM:

![image](https://user-images.githubusercontent.com/129031/71530119-d8cd2e00-28ad-11ea-903b-92f5104546b5.png)

I also tried this entry (`172.21.0.21` was the IP [reported by Traefik](https://take.ms/cfm7T)), to no avail:
```
172.21.0.21 app.example.test
```

Could you give me a pointer on what I need to put in my hosts file, to get this working?

**Comment by davidalger** [comment]
@erikhansen I believe what is the case here is the Docker network which that IP belongs to (likely the `warden` network) is not routable from the Windows VM since the network is contained by the Docker for Mac virtual machine.

Since Traefik is binding it's listening ports to 127.0.0.1 on the host machine, the IP you'll need to specify in the hosts file of the Windows VM is the IP addressing the host machine from VirtualBox network. Should be identical to what you would have configured when Vagrant, Valet+ or any other local dev stack is running on the host really.

I don't have a Windows VM laying around ATM to check, but IIRC `ipconfig` can generally be used to find the correct gateway address which will route to the host machine. This wiki may also help: https://www.thomas-krenn.com/en/wiki/Network_Configuration_in_VirtualBox

**Comment by davidalger** [comment]
@erikhansen Curious if you were able to get this working or not. Any update or notes to share?

**Comment by erikhansen** [comment]
I have not had a chance to get this working yet, so sadly no updates to share.
