### ISSUE TITLE
Mailhog is missing a sendmail binary

### ISSUE THREAD

**Issue by fooman** [davidalger/warden#6]
The current php configures the following sendmail

```
$ cat /etc/php.d/05-additions.ini
sendmail_path = /usr/sbin/sendmail -S mailhog:1025
```

but the image does not include it:

```
www-data@php-fpm:12:51 AM:/var/www/html$ ls -ll /usr/sbin/sendmail
ls: cannot access /usr/sbin/sendmail: No such file or directory
```

Using https://github.com/mailhog/mhsendmail/ and then using the below:

```
$ cat /etc/php.d/05-additions.ini
sendmail_path = "/path/to/mhsendmail --smtp-addr=mailhog:1025"
```
works for me.

**Comment by davidalger** [comment]
@fooman Thanks for this. Looks like we both encountered this oversight with similar timing and it has been fixed by adding `mhsendmail` to the `fpm` images in this commit over on the images repository: https://github.com/davidalger/docker-images-warden/commit/2bfbfbace088a70cdfae7dae1f6e7d0a10674bcb

You should be able to update each of your environments by running the following to pull, build (should the project override and build custom images extending the default ones as some of our projects do), and then re-create running containers with the updated images:
```
warden env pull --ignore-pull-failures \
    && warden env build --pull \
    && warden env up -d \
    && warden sync start          ## Omit this if running on Fedora/Ubuntu hosts
```

Feel free to re-open and let me know if this doesn't resolve it for you. Thanks again!
