### ISSUE TITLE
Allow up part of containers

### ISSUE THREAD

**Issue by Den4ik** [davidalger/warden#98]
I'm using remote db server and in this case it would be good don't start db server for each project where I run `warden up -d`

It would be good to allow configure services at `.env` file.
For example don't run db and varnish

**Comment by erfanimani** [comment]
This would be good. Usually I run the DB on the host instead of out of the container.

**Comment by davidalger** [comment]
Thanks for the suggestion here. It isn't in a ticket here yet, but I have been mulling over the idea of having environment types start with a default set of flags to indicate what services to run and having each service defined in separate files so they can be included individually (or as you mentioned, disabled entirely by overriding those flags in the .env file)

In the case of varnish, there is a `BYPASS_VARNISH` flag available which will send Magento 2 requests directly to Nginx vs through the Varnish container if desired (typically good enough since varnish uses almost no resources at all, so not a big deal most of the time for the container to just be running). Maybe check that out if you need to not use varnish on a project.

I've got a few projects which don't use Elasticsearch, which is basically what got me thinking of this initially as I ended up resorting to putting the following bit in the project's `.warden/warden-env.yml` file to just exit the container on env start:
```
version: "3.5"
services:
  elasticsearch:
    entrypoint: ["echo", "- service is disabled"]   # exit on env start to conserve memory since ES is not used here
    labels:
      - traefik.enable=false
```

Had not thought about use cases where one might want to run the database on the host machine (or heck, somewhere else on their local network) rather than in a Warden controlled container. Interesting use case, and I can see where it might make sense.

No promise as to when I may get to this, but I'd love to see it happen, and I'm going to tag this for 0.3.0 (which again, has no ETA, but eventually we'll get there).

**Comment by davidalger** [comment]
See notes over here: https://github.com/davidalger/warden/pull/150
